name: CD Pipeline

# on:
#   workflow_run:
#     workflows: ["CI Pipeline"]
#     types:
#       - completed
on:
  push:
    branches: ["main"]

jobs:
  deploy-to-ec2:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ec2_instance: [1, 2, 3]
    env:
      EC2_HOST_1: ${{ secrets.EC2_HOST_1 }}
      EC2_HOST_2: ${{ secrets.EC2_HOST_2 }}
      EC2_HOST_3: ${{ secrets.EC2_HOST_3 }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.ec2_instance == 1 && env.EC2_HOST_1 || matrix.ec2_instance == 2 && env.EC2_HOST_2 || env.EC2_HOST_3 }}
          username: ${{env.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          port: 22
          script: |
            # docker pull image
            docker pull james66689/wits_calendar_backend:latest

            if [ "$(docker ps -aq -f name=wits-calendar-backend)" ]; then
                docker stop wits-calendar-backend || true
                docker rm wits-calendar-backend || true
            fi

            docker run -d \
              --name wits-calendar-backend \
              -p 8080:8080 \
              -e TZ=Asia/Taipei \
              -v /home/ubuntu/application.properties:/app/application.properties \
              james66689/wits_calendar_backend:latest
